const fs=require("fs"),{JSDOM}=require("jsdom");
const html=fs.readFileSync("docs/index.html","utf8").replace(/<script[\s\S]*?<\/script>/g,"");
const dom=new JSDOM(html,{url:"https://example.test/",runScripts:"dangerously"});
dom.window.scrollTo=()=>{};
dom.window.cancelAnimationFrame=()=>{};dom.window.requestAnimationFrame=()=>1;
dom.window.HTMLMediaElement.prototype.pause=()=>{};
dom.window.HTMLElement.prototype.scrollTo=()=>{};
dom.window.eval(fs.readFileSync("docs/storage.js","utf8"));
dom.window.eval(fs.readFileSync("docs/harmony.js","utf8"));
dom.window.eval(fs.readFileSync("docs/lessons.js","utf8"));
const q=s=>dom.window.document.querySelector(s),click=s=>q(s).dispatchEvent(new dom.window.MouseEvent("click",{bubbles:true}));
if(!html.includes("-webkit-overflow-scrolling:touch"))throw Error("iOS momentum scrolling failed");
if(q("#slow"))throw Error("legacy speed button still present");
if(q("#lesson-title").textContent!=="A Blues Lick 1")throw Error("initial lick failed");
if(!q("#loop-a-marker")||!q("#loop-b-marker"))throw Error("A/B markers missing");
if(!q("#lick-waveform-canvas")||q("#lick-progress"))throw Error("waveform timeline missing or legacy range remains");
dom.window.lessonPlayer.setLoopPoint("a",.25);dom.window.lessonPlayer.setLoopPoint("b",.75);
if(dom.window.lessonPlayer.getLoopPoints().join(",")!=="0.25,0.75")throw Error("precise A/B loop failed");
click('[data-lick-index="1"]');if(q("#lesson-title").textContent!=="A Blues Lick 2")throw Error("top navigation failed");
click('#course-map [data-lick-index="2"]');if(q("#lesson-title").textContent!=="A Blues Lick 3")throw Error("route navigation failed");
if(!q("#lick-staff img")?.src.includes("fzJaVIxn.png"))throw Error("licensed score failed");
if(!q("#preview-status").textContent.includes("CC BY-SA 4.0"))throw Error("source credit failed");
if(dom.window.document.querySelectorAll("#course-map [data-lick-index]").length!==6||q("#load-more").hidden)throw Error("paginated library failed");
if(!q("#lick-search")||!q("#lick-category")||!q("#lick-key")||!q("#lick-meter"))throw Error("library filters missing");
click("#score-plus");if(q("#score-zoom").textContent!=="125%")throw Error("score zoom failed");
click("#favorite-lick");if(q("#favorite-lick").getAttribute("aria-pressed")!=="true")throw Error("favorite toggle failed");
click("#favorites-filter");if(dom.window.document.querySelectorAll("#course-map [data-lick-index]").length!==1)throw Error("favorite-only filter failed");
click('#course-map [data-lick-index="2"]');if(q("#lesson-title").textContent!=="A Blues Lick 3")throw Error("favorite navigation failed");
click("#lesson-bpm-plus");if(q("#lesson-bpm").textContent!=="85 BPM")throw Error("linked bpm failed");
click("#lesson-original-speed");if(q("#lesson-bpm").textContent!=="120 BPM")throw Error("original speed reset failed");
if(!q("#toggle-backing")||!q("#toggle-backing").title.includes("实时生成"))throw Error("generated backing controls failed");
click("#toggle-demo");if(q("#toggle-demo").getAttribute("aria-pressed")!=="false")throw Error("backing-only mode failed");
dom.window.lessonPlayer.select(14);if(q("#lesson-title").textContent!=="A ii–V–I Lick 1")throw Error("category navigation failed");
click('#clear-filters');
q('#lick-harmony').value='2-5-1';q('#lick-harmony').dispatchEvent(new dom.window.Event('input'));
if(!q('#course-map').textContent.includes('Bm7'))throw Error('degree harmony search failed');
q('#lick-harmony').value='Dm7 G7 Cmaj7';q('#lick-harmony').dispatchEvent(new dom.window.Event('input'));
if(q('#course-map [data-lick-index]'))throw Error('wrong-key harmony match');
click('#harmony-transpose');if(!q('#course-map [data-lick-index]'))throw Error('transposed harmony match failed');
q('#lick-harmony').value='H7';q('#lick-harmony').dispatchEvent(new dom.window.Event('input'));
if(q('#harmony-error').hidden||q('#course-map [data-lick-index]'))throw Error('invalid harmony must not return results');
click('#clear-filters');
dom.window.eval(fs.readFileSync('docs/assets/licks/guitar-index.js','utf8'));
if(!q('#library-count').textContent.includes('2525'))throw Error('full static index ingestion failed');
q('#lick-harmony').value='iiø7 V7 i7';q('#lick-harmony').dispatchEvent(new dom.window.Event('input'));
if(!q('#course-map [data-lick-index]'))throw Error('real minor ii-V-i filter failed');
if(q('#scale-lab'))throw Error('removed scale trainer remains');
console.log('PASS lessons: playback controls, favorites, original speed, A/B, zoom, 2525-entry index, harmony search and invalid input');
setImmediate(()=>dom.window.close());
