const fs=require("fs"),{JSDOM}=require("jsdom");
const html=fs.readFileSync("docs/index.html","utf8").replace(/<script[\s\S]*?<\/script>/g,"");
const dom=new JSDOM(html,{url:"https://example.test/",runScripts:"dangerously"});
dom.window.scrollTo=()=>{};
dom.window.cancelAnimationFrame=()=>{};dom.window.requestAnimationFrame=()=>1;
dom.window.HTMLMediaElement.prototype.pause=()=>{};
dom.window.HTMLElement.prototype.scrollTo=()=>{};
dom.window.eval(fs.readFileSync("docs/lessons.js","utf8"));
const q=s=>dom.window.document.querySelector(s),click=s=>q(s).dispatchEvent(new dom.window.MouseEvent("click",{bubbles:true}));
if(!html.includes("-webkit-overflow-scrolling:touch"))throw Error("iOS momentum scrolling failed");
if(q("#slow"))throw Error("legacy speed button still present");
if(q("#lesson-title").textContent!=="A Blues Lick 1")throw Error("initial lick failed");
if(!q("#loop-a-marker")||!q("#loop-b-marker"))throw Error("A/B markers missing");
if(q("#scale-type").options.length<20)throw Error("scale library incomplete");
if(q("#scale-name").textContent!=="A Mixolydian（混合利底亚）")throw Error("default scale trainer failed");
if(q("#scale-notes").textContent.replace(/\s/g,"")!=="A1B2C♯3D4E5F♯6G♭7A8")throw Error("scale note rendering failed");
if(!q("#scale-feel")||dom.window.document.querySelectorAll("[data-scale-lick]").length!==2)throw Error("scale feel or lick controls missing");
if(!q("#scale-character").textContent.includes("♭7"))throw Error("scale listening cue missing");
if(!q("#scale-lick-list").textContent.includes("级数（↑ 高八度）"))throw Error("scale lick degrees missing");
q("#scale-root").value="6";q("#scale-root").dispatchEvent(new dom.window.Event("change"));q("#scale-type").value="ionian";q("#scale-type").dispatchEvent(new dom.window.Event("change"));
if(!q("#scale-notes").textContent.includes("E♯"))throw Error("enharmonic scale spelling failed");
dom.window.lessonPlayer.setLoopPoint("a",.25);dom.window.lessonPlayer.setLoopPoint("b",.75);
if(dom.window.lessonPlayer.getLoopPoints().join(",")!=="0.25,0.75")throw Error("precise A/B loop failed");
click('[data-lick-index="1"]');if(q("#lesson-title").textContent!=="A Blues Lick 2")throw Error("top navigation failed");
click('#course-map [data-lick-index="2"]');if(q("#lesson-title").textContent!=="A Blues Lick 3")throw Error("route navigation failed");
if(!q("#lick-staff img")?.src.includes("fzJaVIxn.png"))throw Error("licensed score failed");
if(!q("#preview-status").textContent.includes("CC BY-SA 4.0"))throw Error("source credit failed");
if(dom.window.document.querySelectorAll("#course-map [data-lick-index]").length!==20)throw Error("expanded library failed");
click("#score-plus");if(q("#score-zoom").textContent!=="125%")throw Error("score zoom failed");
click("#favorite-lick");if(!q("#favorite-lick").textContent.includes("已收藏"))throw Error("favorite toggle failed");
if(dom.window.document.querySelectorAll("#harmony-map [data-lick-index]").length!==1)throw Error("favorite-only list failed");
if(q("#favorite-count").textContent!=="★ 1")throw Error("favorite count failed");
click('#harmony-map [data-lick-index="2"]');if(q("#lesson-title").textContent!=="A Blues Lick 3")throw Error("favorite navigation failed");
click("#lesson-bpm-plus");if(q("#lesson-bpm").textContent!=="85 BPM")throw Error("linked bpm failed");
click("#lesson-original-speed");if(q("#lesson-bpm").textContent!=="120 BPM")throw Error("original speed reset failed");
if(!q("#toggle-backing")||!q("#preview-status").textContent.includes("实时生成"))throw Error("generated backing controls failed");
click("#toggle-demo");if(q("#toggle-demo").textContent!=="示范音：关")throw Error("backing-only mode failed");
if(!q("#bar-detail").textContent.includes("半音导向"))throw Error("lick theory failed");
dom.window.lessonPlayer.select(14);if(q("#lesson-title").textContent!=="A ii–V–I Lick 1")throw Error("category navigation failed");
console.log("lesson smoke test passed");
