const fs=require("fs"),{JSDOM}=require("jsdom");
const html=fs.readFileSync("docs/index.html","utf8").replace(/<script[\s\S]*?<\/script>/g,"");
const dom=new JSDOM(html,{url:"https://example.test/",runScripts:"dangerously"});
dom.window.scrollTo=()=>{};
dom.window.cancelAnimationFrame=()=>{};dom.window.requestAnimationFrame=()=>1;
dom.window.HTMLMediaElement.prototype.pause=()=>{};
dom.window.eval(fs.readFileSync("docs/lessons.js","utf8"));
const q=s=>dom.window.document.querySelector(s),click=s=>q(s).dispatchEvent(new dom.window.MouseEvent("click",{bubbles:true}));
if(q("#lesson-title").textContent!=="A Blues Lick 1")throw Error("initial lick failed");
click('[data-lick-index="1"]');if(q("#lesson-title").textContent!=="A Blues Lick 2")throw Error("top navigation failed");
click('#harmony-map [data-lick-index="2"]');if(q("#lesson-title").textContent!=="A Blues Lick 3")throw Error("map navigation failed");
if(!q("#lick-staff img")?.src.includes("fzJaVIxn.png"))throw Error("licensed score failed");
if(!q("#preview-status").textContent.includes("CC BY-SA 4.0"))throw Error("source credit failed");
if(q("#complete-lesson").textContent!=="下一条 →")throw Error("next label failed");
click("#complete-lesson");if(q("#lesson-title").textContent!=="A Blues Lick 4")throw Error("next navigation failed");
click("#prev-lesson");if(q("#lesson-title").textContent!=="A Blues Lick 3")throw Error("previous navigation failed");
console.log("lesson smoke test passed");
