const fs=require('node:fs'),assert=require('node:assert/strict');
const {JSDOM}=require('jsdom');
const html=fs.readFileSync('docs/index.html','utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'');
const dom=new JSDOM(html,{url:'https://rexrockya.github.io/tuner/',runScripts:'outside-only'});
const w=dom.window,d=w.document;let pauses=0,backs=0;
w.scorePlayer={pause(){pauses++},showLibrary(){backs++;w.scoreReader.close()}};
w.eval(fs.readFileSync('docs/score-reader.js','utf8'));
const player=d.getElementById('sheet-player'),settings=d.getElementById('sheet-settings-toggle');
assert.equal(d.querySelectorAll('#sheet-play').length,1);
assert.ok(player.querySelector('.sheet-transport .sheet-mixer'));
assert.equal(d.querySelectorAll('.sheet-transport > :not(.sheet-advanced)').length,3);
for(const id of ['sheet-instrument-volume','sheet-click-volume','sheet-bpm-plus','sheet-zoom-plus','sheet-rewind','sheet-metronome'])assert.ok(d.getElementById(id).closest('.sheet-advanced'));
const upload=JSON.parse(fs.readFileSync('docs/assets/scores/violin-upload-2026-09-06-1.json','utf8'));
w.scoreReader.bind(upload);
assert.match(d.getElementById('sheet-reader-label').textContent,/11 小节.*待校对/);
assert.equal(d.getElementById('sheet-original-toggle').hidden,false);
assert.equal(d.getElementById('sheet-original-image').hasAttribute('src'),false,'source image is lazy');
settings.click();assert.equal(settings.getAttribute('aria-expanded'),'true');
assert.ok(player.classList.contains('sheet-settings-open'));
d.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape'}));
assert.equal(settings.getAttribute('aria-expanded'),'false');
d.getElementById('sheet-original-toggle').click();
assert.equal(pauses,1);assert.equal(d.getElementById('sheet-canvas').hidden,true);
assert.equal(d.getElementById('sheet-original-view').hidden,false);
assert.match(d.getElementById('sheet-original-image').src,/tuner\/assets\/scores\/uploads\/2026-09-06\/page-1.png$/);
assert.match(d.getElementById('sheet-original-view').textContent,/试听仍为已转录部分/);
d.getElementById('sheet-original-toggle').click();assert.equal(d.getElementById('sheet-canvas').hidden,false);
settings.click();d.getElementById('sheet-reader-back').click();assert.equal(backs,1);assert.equal(settings.getAttribute('aria-expanded'),'false');
w.scoreReader.bind({...upload,id:'fur-elise',reviewNotice:undefined});assert.equal(d.getElementById('sheet-original-toggle').hidden,true);
const css=fs.readFileSync('docs/score-controls.css','utf8');
assert.match(css,/height:100dvh/);assert.match(css,/\.sheet-score-scroll\{flex:1 1 auto;min-height:0;height:auto/);
assert.match(css,/sheet-player:not\(\.sheet-settings-open\) \.sheet-advanced\{display:none/);
assert.match(css,/max-height:70dvh/);assert.match(css,/safe-area-inset-bottom/);
assert.match(fs.readFileSync('docs/scores.js','utf8'),/ui\.player\.requestFullscreen/);
dom.window.close();
console.log('PASS: single transport, compact/expanded controls, Escape/back reset, lazy full image, explicit playback limit, mobile dynamic viewport and safe-area contracts');
