const fs=require('node:fs'),assert=require('node:assert/strict');
const {JSDOM}=require('jsdom');
const html=fs.readFileSync('docs/index.html','utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'');
const dom=new JSDOM(html,{url:'https://rexrockya.github.io/tuner/',runScripts:'outside-only'});
const w=dom.window,d=w.document;let pauses=0,backs=0;
w.scorePlayer={pause(){pauses++},showLibrary(){backs++;w.scoreReader.close()}};
w.eval(fs.readFileSync('docs/score-reader.js','utf8'));
const player=d.getElementById('sheet-player'),settings=d.getElementById('sheet-settings-toggle');
assert.equal(d.querySelectorAll('#sheet-play').length,1);
assert.ok(player.querySelector('.sheet-transport .sheet-mixer'));
assert.equal(d.querySelectorAll('.sheet-transport > :not(.sheet-advanced)').length,3);
for(const id of ['sheet-instrument-volume','sheet-click-volume','sheet-bpm-plus','sheet-zoom-plus','sheet-rewind','sheet-metronome'])assert.ok(d.getElementById(id).closest('.sheet-advanced'));
const upload=JSON.parse(fs.readFileSync('docs/assets/scores/violin-upload-2026-09-06-1.json','utf8'));
w.scoreReader.bind(upload);
assert.match(d.getElementById('sheet-reader-label').textContent,/35 小节.*待校对/);
assert.equal(d.getElementById('sheet-original-toggle').hidden,false);
assert.equal(d.getElementById('sheet-original-image').hasAttribute('src'),false,'source image is lazy');
settings.click();assert.equal(settings.getAttribute('aria-expanded'),'true');
assert.ok(player.classList.contains('sheet-settings-open'));
d.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape'}));
assert.equal(settings.getAttribute('aria-expanded'),'false');
d.getElementById('sheet-original-toggle').click();
assert.equal(pauses,1);assert.equal(d.getElementById('sheet-canvas').hidden,true);
assert.equal(d.getElementById('sheet-original-view').hidden,false);
assert.match(d.getElementById('sheet-original-image').src,/tuner\/assets\/scores\/uploads\/2026-09-06\/page-1.png$/);
assert.match(d.getElementById('sheet-original-view').textContent,/整页可播放校对版/);
d.getElementById('sheet-original-toggle').click();assert.equal(d.getElementById('sheet-canvas').hidden,false);
settings.click();d.getElementById('sheet-reader-back').click();assert.equal(backs,1);assert.equal(settings.getAttribute('aria-expanded'),'false');
w.scoreReader.bind({...upload,id:'fur-elise',reviewNotice:undefined});assert.equal(d.getElementById('sheet-original-toggle').hidden,true);
const canvas=d.getElementById('sheet-canvas'),scroll=d.getElementById('sheet-score-scroll');
let zoom=1,anchor,clicked=0,fits=0;
w.scorePlayer.getZoom=()=>zoom;
w.scorePlayer.setZoom=(value,point)=>{zoom=value;anchor=point;};
w.scorePlayer.fitWidth=()=>{fits++;zoom=1;};
canvas.addEventListener('click',()=>clicked++);
const pointer=(type,id,x,y)=>{
 const event=new w.Event(type,{bubbles:true,cancelable:true});
 Object.assign(event,{pointerId:id,pointerType:'touch',button:0,clientX:x,clientY:y});
 canvas.dispatchEvent(event);
};
pointer('pointerdown',1,100,100);pointer('pointerdown',2,200,100);
assert.equal(w.scoreReader.isInteracting(),true);
pointer('pointermove',2,300,100);assert.equal(zoom,2);assert.equal(anchor.x,150);
const note=d.createElement('span');canvas.append(note);
const transfer=new w.Event('lostpointercapture',{bubbles:true});Object.assign(transfer,{pointerId:2});note.dispatchEvent(transfer);
pointer('pointermove',2,400,100);assert.equal(zoom,3,'capture transfer from a measure does not end pinch');
canvas.click();assert.equal(clicked,0,'pinching never seeks a measure');
pointer('pointerup',2,300,100);
const top=scroll.scrollTop;pointer('pointermove',1,80,70);assert.equal(scroll.scrollTop,top+30);
pointer('pointercancel',1,80,70);
w.scoreReader.close();assert.equal(w.scoreReader.isInteracting(),false);
canvas.click();assert.equal(clicked,1,'ordinary measure clicks remain available');
d.getElementById('sheet-fit-width').click();assert.equal(fits,1);assert.equal(zoom,1);
settings.click();w.innerWidth=844;w.dispatchEvent(new w.Event('resize'));
assert.equal(settings.getAttribute('aria-expanded'),'false','rotation collapses settings');
const css=fs.readFileSync('docs/score-controls.css','utf8');
assert.match(css,/max-height:600px\) and \(max-width:1200px/);
assert.match(css,/#sheet-canvas\{min-width:0;padding:0;touch-action:none/);
assert.match(css,/height:100dvh/);assert.match(css,/\.sheet-score-scroll\{flex:1 1 auto;min-height:0;height:auto/);
assert.match(css,/sheet-player:not\(\.sheet-settings-open\) \.sheet-advanced\{display:none/);
assert.match(css,/max-height:70dvh/);assert.match(css,/safe-area-inset-bottom/);
assert.match(fs.readFileSync('docs/scores.js','utf8'),/ui\.player\.requestFullscreen/);
dom.window.close();
console.log('PASS: single transport, compact/expanded controls, Escape/back reset, lazy full image, explicit playback limit, mobile dynamic viewport and safe-area contracts');
