import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
await import('../docs/sound-dsp.js');
await import('../docs/loudness-dsp.js');
const {Meter,db,weight,centers}=globalThis.SoundDSP;
const near=(a,b,e=.04)=>assert.ok(Math.abs(a-b)<e, a+' expected '+b);
for(const rate of [44100,48000]){
 const n=4096,k=Math.round(1000*n/rate),f=k*rate/n;
 const tone=Float32Array.from({length:n},(_,i)=>.5*Math.sin(2*Math.PI*k*i/n));
 const meter=new Meter(rate);let d;
 for(let j=0;j<120;j++)d=meter.analyze(tone);
 near(db(d.leq[2]),-9.0309);near(db(d.leq[0])-db(d.leq[2]),db(weight(f,'A')));
 near(db(d.fast[2]),-9.0309);near(db(d.slow[2]),-9.0309);
 near(db(d.sel[2])-db(d.leq[2]),10*Math.log10(d.seconds));
 near(db(d.peak),-6.0206);
 assert.equal(centers[d.bands.indexOf(Math.max(...d.bands.filter(x=>x!==null)))],1000);
 assert.equal(d.clipped,0);near(d.seconds,120*n/rate,1e-8);
 meter.reset();d=meter.analyze(new Float32Array(n));
 assert.equal(db(d.leq[2]),-Infinity);assert.equal(d.peak,0);assert.ok(d.fast.every(x=>x===0));
 meter.reset();meter.analyze(new Float32Array(n).fill(.1));d=meter.analyze(new Float32Array(n).fill(1));
 near(db(d.leq[2]),10*Math.log10(.505));assert.equal(d.clipped,n);
 near(d.fast[2],.01*(1-Math.exp(-n/rate/.125))*Math.exp(-n/rate/.125)+(1-Math.exp(-n/rate/.125)),1e-7);
 const lowK=8,low=new Meter(rate).analyze(Float32Array.from({length:n},(_,i)=>.5*Math.sin(2*Math.PI*lowK*i/n)));
 near(db(low.leq[0])-db(low.leq[2]),db(weight(lowK*rate/n,'A')));
}
near(db(weight(1000,'A')),0,.01);near(db(weight(1000,'C')),0,.01);
near(db(weight(100,'A')),-19.14,.1);near(db(weight(100,'C')),-.3,.1);
near(db(weight(10000,'A')),-2.49,.1);
let Worklet;
const sandbox={ProgrammeLoudness:globalThis.ProgrammeLoudness,SoundDSP:globalThis.SoundDSP,sampleRate:48000,AudioWorkletProcessor:class{constructor(){this.port={postMessage:d=>this.messages.push(d)};this.messages=[];}},registerProcessor:(name,klass)=>{Worklet=klass;}};
vm.runInNewContext(fs.readFileSync('docs/sound-worklet.js','utf8').replace(/^.*import .*$/gm,''),sandbox);
const work=new Worklet(),block=new Float32Array(128).fill(.1);
for(let j=0;j<32;j++)work.process([[block]]);
assert.equal(work.messages.length,1);near(work.messages[0].seconds,4096/48000,1e-10);
work.port.onmessage({data:{type:'reset',generation:1}});
for(let j=0;j<32;j++)work.process([[block]]);
assert.equal(work.messages[1].generation,1);near(work.messages[1].seconds,4096/48000,1e-10);
work.process([]);assert.equal(work.messages.length,2);
console.log('PASS sound DSP: 44.1/48 kHz tone energy, A/C weighting, frequency band, energy Leq, SEL duration, Fast/Slow, clipping, silence, worklet blocks/reset');

const stereo=new Worklet();
for(let j=0;j<32;j++)stereo.process([[new Float32Array(128).fill(.25),new Float32Array(128).fill(-.25)]]);
near(db(stereo.messages[0].leq[2]),20*Math.log10(.25));
near(db(stereo.messages[0].peak),20*Math.log10(.25));
const oneSide=new Worklet();
for(let j=0;j<32;j++)oneSide.process([[new Float32Array(128).fill(.25),new Float32Array(128)]]);
near(db(oneSide.messages[0].leq[2]),20*Math.log10(.25)-3.0103);
console.log('PASS stereo: opposite phase retains energy; single active channel averages power without cancellation');
