const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),vm=require('node:vm');const{ROOT,setup,tick,raw}=require('./harness.cjs');
(async()=>{
const h=setup({skipApp:true,fetch:(url,options,response)=>url.endsWith('.mp3')?{...response(),arrayBuffer:async()=>new ArrayBuffer(4)}:response({user:null})});
const media=[],createElement=h.d.createElement.bind(h.d);h.d.createElement=(name,options)=>{const element=createElement(name,options);if(name.toLowerCase()==="audio")media.push(element);return element};
h.w.OfflineAudioContext=class{async decodeAudioData(){return{length:720,numberOfChannels:1,duration:8,getChannelData:()=>new Float32Array(720)}}};
const scriptSources=[...raw.matchAll(/<script\b([^>]*)\bsrc="([^"]+)"[^>]*><\/script>/g)].map(match=>({attrs:match[1],src:match[2]}));assert.ok(scriptSources.length>=10);const loaded=[];
for(const script of scriptSources){assert.match(script.attrs,/\bdefer\b/,script.src+' must defer');const url=new URL(script.src,'https://rexrockya.github.io/tuner/');assert.equal(url.origin,'https://rexrockya.github.io');const file=path.join(ROOT,'docs',decodeURIComponent(url.pathname.replace(/^\/tuner\//,'')));assert.ok(fs.existsSync(file),file);Object.defineProperty(h.d,'currentScript',{value:{src:url.href},configurable:true});vm.runInContext(fs.readFileSync(file,'utf8'),h.dom.getInternalVMContext(),{filename:file});loaded.push(script.src)}
await tick();assert.equal(h.q('.tab.active').dataset.page,'tools');assert.ok(h.w.lessonPlayer?.activate&&h.w.scorePlayer&&h.w.metronome&&h.w.tunerPitch&&h.w.siteAssets);assert.equal(h.d.querySelectorAll('script[src]').length,0,'default tools inserted a deferred feature library');assert.equal(h.calls.filter(call=>/\.mp3(?:[?#]|$)/.test(call.url||'')).length,0,'default tools fetched hidden MP3 waveform');assert.equal(h.calls.filter(call=>/vendor\/|guitar-index\.js/.test(call.url||'')).length,0);assert.equal(h.w.practiceStudio,undefined);assert.equal(h.w.practiceAudio,undefined);assert.equal(h.w.Tone,undefined);assert.equal(h.w.opensheetmusicdisplay,undefined);assert.equal(h.w.fflate,undefined);assert.equal(media[0].preload,'none');assert.equal(h.errors.length,0,h.errors.join('\n'));console.log('PASS full defer boot: '+loaded.length+' real scripts, tools ready, zero vendor/index/MP3 waveform requests');
h.click('.tab[data-page="lesson"]');await tick();assert.equal(h.q('.tab.active').dataset.page,'lesson');assert.equal(h.d.querySelectorAll('script[src*="guitar-index.js"]').length,1);assert.equal(h.calls.filter(call=>/\.mp3(?:[?#]|$)/.test(call.url||'')).length,1);assert.equal(media[0].preload,'metadata');assert.equal(h.d.querySelectorAll('script[src*="assets/vendor/"]').length,0,'lesson activation unnecessarily loaded score/tone vendor');h.w.eval(fs.readFileSync(ROOT+'/docs/assets/licks/guitar-index.js','utf8'));assert.match(h.q('#library-count').textContent,/2525/);h.click('.tab[data-page="tuner"]');h.click('.tab[data-page="lesson"]');await tick();assert.equal(h.d.querySelectorAll('script[src*="guitar-index.js"]').length,1);assert.equal(h.calls.filter(call=>/\.mp3(?:[?#]|$)/.test(call.url||'')).length,1);assert.equal(h.errors.length,0,h.errors.join('\n'));console.log('PASS lesson activation: index + waveform load exactly once, 2525-entry ingestion, vendor remains lazy');h.close();
})().catch(error=>{console.error(error);process.exitCode=1});
