const assert=require('assert/strict'),fs=require('fs');const{setup,toneStub,tick}=require('./harness.cjs');const results=[];
const test=async(name,fn)=>{try{await fn();results.push({name,status:'PASS'})}catch(e){results.push({name,status:'FAIL',detail:e.stack})}};
(async()=>{
await test('Jam piano roll add/move/resize/delete + scale lock + zoom/monitor persistence',async()=>{const h=setup();h.w.qa.jamOpen('night-lamp');h.click('[data-action="claim"][data-role="lead"]');let roll=h.q('[data-roll]');roll.getBoundingClientRect=()=>({left:0,top:0,width:800,height:160});roll.dispatchEvent(new h.w.MouseEvent('pointerdown',{bubbles:true,clientX:200,clientY:50}));let room=h.w.qa.current(),take=room.draft.sections[room.draft.activeSection];assert.equal(take.events.length,1);let initial={...take.events[0]};let note=h.q('[data-note-id]');roll=h.q('[data-roll]');roll.getBoundingClientRect=()=>({left:0,top:0,width:800,height:160});note.dispatchEvent(new h.w.MouseEvent('pointerdown',{bubbles:true,clientX:200,clientY:50}));h.d.dispatchEvent(new h.w.MouseEvent('pointermove',{bubbles:true,clientX:300,clientY:30}));h.d.dispatchEvent(new h.w.MouseEvent('pointerup',{bubbles:true}));assert.ok(take.events[0].s>initial.s);assert.ok(take.events[0].n>=initial.n);let d=take.events[0].d;roll=h.q('[data-roll]');roll.getBoundingClientRect=()=>({left:0,top:0,width:800,height:160});h.q('[data-resize-note]').dispatchEvent(new h.w.MouseEvent('pointerdown',{bubbles:true,clientX:300,clientY:30}));h.d.dispatchEvent(new h.w.MouseEvent('pointermove',{bubbles:true,clientX:350,clientY:30}));h.d.dispatchEvent(new h.w.MouseEvent('pointerup',{bubbles:true}));assert.ok(take.events[0].d>d);h.click('[data-action="zoom-in"]');assert.equal(room.draft.zoom,1.25);h.q('#jam-scale-lock').checked=false;h.q('#jam-scale-lock').dispatchEvent(new h.w.Event('change',{bubbles:true}));assert.equal(room.draft.scaleLock,false);const monitor=h.q('[data-monitor="lead"]');monitor.value=55;monitor.dispatchEvent(new h.w.Event('input',{bubbles:true}));monitor.dispatchEvent(new h.w.Event('change',{bubbles:true}));assert.equal(room.draft.monitorMix.lead,55);h.click('[data-action="delete-note"]');assert.equal(take.events.length,0);assert.equal(h.errors.length,0,h.errors.join('\n'));h.close()});
await test('Jam record count-in / stop / quantized note event / pause timer cleanup',async()=>{const h=setup();toneStub(h.w);h.w.qa.jamOpen('night-lamp');h.click('[data-action="claim"][data-role="lead"]');h.click('[data-action="record"]');await tick();assert.equal(h.intervals.size,1);const interval=[...h.intervals.values()][0];for(let i=0;i<4;i++)interval.fn();assert.ok(h.w.qa.getRecording());assert.equal(h.intervals.size,0);await h.w.qa.jamPress('test',60);h.w.qa.jamRelease('test');h.click('[data-action="record"]');assert.equal(h.w.qa.getRecording(),null);const room=h.w.qa.current();assert.equal(room.draft.sections[room.draft.activeSection].events.length,1);assert.equal(room.draft.sections[room.draft.activeSection].events[0].d,1);h.click('[data-action="record"]');await tick();assert.equal(h.intervals.size,1);h.click('[data-action="close"]');assert.equal(h.intervals.size,0);assert.equal(h.w.qa.getRecording(),null);h.close()});
await test('Jam no Tone engine gives recoverable user-visible error',async()=>{const h=setup();h.click('[data-preview="night-lamp"]');await tick();assert.equal(h.w.qa.getSound().roomId,null);assert.match(h.q('#jam-toast').textContent,/引擎|音色载入失败/);h.close()});
await test('Jam playback pending then navigate must not start hidden audio',async()=>{let resolve;const h=setup();toneStub(h.w,{start:()=>new Promise(r=>resolve=r)});h.click('.tab[data-page="jam"]');h.click('[data-preview="night-lamp"]');h.click('.tab[data-page="lesson"]');resolve();await tick();assert.equal(h.w.qa.getSound().roomId,null,'Jam starts after leaving page while audio start pending');h.close()});
await test('Microphone setup failure after accepted permission must stop stream',async()=>{const h=setup();h.w.AudioContext=class{constructor(){throw Error('Audio unavailable')}};h.click('#toggle');await tick();assert.equal(h.mic().stopped,1,'accepted stream leaked on AudioContext init exception');assert.equal(h.q('#error').style.display,'block');h.close()});
await test('Jam title/password text fields ignore instrument hotkeys',async()=>{const h=setup();const t=toneStub(h.w);h.w.qa.jamOpen('night-lamp');h.click('[data-action="claim"][data-role="lead"]');const field=h.q('#account-form').elements.username;field.dispatchEvent(new h.w.KeyboardEvent('keydown',{key:'a',code:'KeyA',bubbles:true}));await tick();assert.equal(t.log.filter(v=>v[0]==='attack').length,0);h.close()});

await test('Jam pending recording then close dialog must not create countdown',async()=>{let resolve;const h=setup();toneStub(h.w,{start:()=>new Promise(r=>resolve=r)});h.w.qa.jamOpen('night-lamp');h.click('[data-action="claim"][data-role="lead"]');h.click('[data-action="record"]');h.click('[data-action="close"]');resolve();await tick();assert.equal(h.intervals.size,0);assert.equal(h.w.qa.getRecording(),null);assert.equal(h.q('#jam-room-dialog').open,false);h.close()});
await test('Jam window blur releases all held notes',async()=>{const h=setup();const t=toneStub(h.w);h.w.qa.jamOpen('night-lamp');h.click('[data-action="claim"][data-role="lead"]');await h.w.qa.jamPress('key-KeyA',60);assert.equal(h.w.qa.getHeld().size,1);h.w.dispatchEvent(new h.w.Event('blur'));assert.equal(h.w.qa.getHeld().size,0);assert.ok(t.log.some(v=>v[0]==='release'));h.close()});
await test('Hashchange consistently switches all five pages and score subroutes',async()=>{const h=setup();for(const[hash,page]of[['#jam','jam'],['#metro','metro'],['#lessons','lesson'],['#lick/A1','lesson'],['#scores','sheet'],['#score/fur-elise','sheet'],['','tuner']]){h.w.history.replaceState(null,'','/tuner/'+hash);h.w.dispatchEvent(new h.w.HashChangeEvent('hashchange'));assert.equal(h.q('.tab.active').dataset.page,page);assert.equal(h.q('.tab[aria-current="page"]').dataset.page,page)}assert.ok(h.calls.some(v=>v.scoreOpen==='fur-elise'));assert.equal(h.errors.length,0,h.errors.join('\n'));h.close()});
process.exitCode=results.some(result=>result.status==='FAIL')?1:0;for(const r of results)console.log(`${r.status} ${r.name}${r.detail?'\n '+r.detail.split('\n').slice(0,4).join('\n '):''}`);console.log(JSON.stringify({pass:results.filter(r=>r.status==='PASS').length,fail:results.filter(r=>r.status==='FAIL').length}));})();
