const fs=require('node:fs'),assert=require('node:assert/strict');const{ROOT,setup,tick}=require('./harness.cjs');const results=[];
const load=h=>{Object.defineProperty(h.d,'currentScript',{value:{src:'https://rexrockya.github.io/tuner/asset-loader.js'},configurable:true});h.w.eval(fs.readFileSync(ROOT+'/docs/asset-loader.js','utf8'));};
async function test(name,fn){try{await fn();results.push({name,status:'PASS'})}catch(error){results.push({name,status:'FAIL',detail:error.stack})}}
(async()=>{
await test('Asset loader default initialization is request-free',async()=>{const h=setup({skipApp:true});load(h);await tick();assert.equal(h.d.querySelectorAll('script[src]').length,0);assert.equal(h.calls.length,0);assert.equal(h.timeouts.size,0);h.close()});
await test('Asset loader same-library concurrency deduplicates and uses local URLs',async()=>{const h=setup({skipApp:true});load(h);const first=h.w.siteAssets.load('tone'),second=h.w.siteAssets.load('tone');assert.equal(first,second);assert.equal(h.d.querySelectorAll('script[src]').length,1);const script=h.q('script[src]');assert.equal(script.src,'https://rexrockya.github.io/tuner/assets/vendor/tone-14.9.17.js');h.w.Tone={ready:true};script.onload();assert.equal(await first,h.w.Tone);assert.equal(h.timeouts.size,0);assert.equal(await h.w.siteAssets.load('tone'),h.w.Tone);assert.equal(h.d.querySelectorAll('script[src]').length,1);h.close()});
await test('Asset loader validates expected global and permits retry after false success',async()=>{const h=setup({skipApp:true});load(h);const pending=h.w.siteAssets.load('zip');const rejection=assert.rejects(pending,/资源载入失败/);h.q('script[src]').onload();await rejection;assert.equal(h.d.querySelectorAll('script[src]').length,0);const retry=h.w.siteAssets.load('zip');h.w.fflate={ready:true};h.q('script[src]').onload();assert.equal(await retry,h.w.fflate);h.close()});
await test('Asset loader network failure removes script and permits clean retry',async()=>{const h=setup({skipApp:true});load(h);const pending=h.w.siteAssets.load('score');const rejection=assert.rejects(pending,/资源载入失败/);const failed=h.q('script[src]');failed.onerror();await rejection;assert.equal(failed.isConnected,false);assert.equal(h.timeouts.size,0);const retry=h.w.siteAssets.load('score');const script=h.q('script[src]');assert.notEqual(script,failed);assert.equal(script.src,'https://rexrockya.github.io/tuner/assets/vendor/opensheetmusicdisplay-2.1.2.min.js');h.w.opensheetmusicdisplay={ready:true};script.onload();await retry;h.close()});
await test('Asset loader timeout removes script and permits retry',async()=>{const h=setup({skipApp:true});load(h);const pending=h.w.siteAssets.load('tone');const rejection=assert.rejects(pending,/超时/);assert.equal(h.timeouts.size,1);const timeout=[...h.timeouts.values()][0];assert.equal(timeout.ms,15000);timeout.fn();await rejection;assert.equal(h.d.querySelectorAll('script[src]').length,0);const retry=h.w.siteAssets.load('tone');h.w.Tone={ready:true};h.q('script[src]').onload();await retry;h.close()});
await test('Asset loader saveData disables prewarming; unknown names reject',async()=>{const h=setup({skipApp:true});load(h);Object.defineProperty(h.w.navigator,'connection',{value:{saveData:true},configurable:true});h.w.siteAssets.warm('tone');await tick();assert.equal(h.timeouts.size,0);assert.equal(h.d.querySelectorAll('script[src]').length,0);await assert.rejects(h.w.siteAssets.load('unknown'),/未知资源/);h.close()});
process.exitCode=results.some(result=>result.status==='FAIL')?1:0;for(const r of results)console.log(`${r.status} ${r.name}${r.detail?'\n '+r.detail:''}`);console.log(JSON.stringify({pass:results.filter(r=>r.status==='PASS').length,fail:results.filter(r=>r.status==='FAIL').length}));})();
