const fs=require('fs'),assert=require('assert/strict');const {ROOT,setup,tick}=require('./harness.cjs');const results=[];
const load=(h,file)=>{Object.defineProperty(h.d,'currentScript',{value:{src:'https://rexrockya.github.io/tuner/'+file},configurable:true});h.w.eval(fs.readFileSync(ROOT+'/docs/'+file,'utf8'));};
async function test(name,fn){try{await fn();results.push({name,status:'PASS'})}catch(e){results.push({name,status:'FAIL',detail:e.stack})}}
(async()=>{
await test('Scores embedded catalog: 10 piano / 3 violin; local search/favorite',async()=>{const h=setup();load(h,'scores.js');await tick();assert.equal(h.q('#score-piano-grid').querySelectorAll('.score-card').length,10);assert.equal(h.q('#score-violin-grid').querySelectorAll('.score-card').length,3);h.q('#score-search').value='Elise';h.q('#score-search').dispatchEvent(new h.w.Event('input'));assert.equal(h.q('#score-piano-grid').querySelectorAll('.score-card').length,1);assert.match(h.q('#score-piano-grid').textContent,/Elise/);h.click('#score-piano-grid .score-favorite');assert.equal(h.q('#score-favorite-grid').querySelectorAll('.score-card').length,1);h.close()});
await test('Flat connect/token clear/profile/private collection merge/disconnect (mock only)',async()=>{const h=setup({fetch:(url,opts,res)=>{if(url.includes('api.flat.io'))return res(url.endsWith('/me')?{id:'qa',printableName:'QA Test'}:[{id:'score-1',title:'QA Song',user:{username:'qa'}}]);return res({user:null})}});load(h,'scores.js');await tick();await assert.rejects(h.w.scorePlayer.connectFlat(''),/Token/);h.click('#score-flat-open');assert.equal(h.q('#score-flat-dialog').open,true);h.q('#score-flat-token').value='fake-token-no-real-access';h.q('#score-flat-form').dispatchEvent(new h.w.Event('submit',{bubbles:true,cancelable:true}));await tick();assert.equal(h.q('#score-flat-token').value,'');assert.equal(h.q('#score-flat-connect').disabled,false);assert.match(h.q('#score-flat-status').textContent,/QA Test/);const scores=await h.w.scorePlayer.loadFlatScores();assert.equal(scores.length,1);assert.equal(scores[0].id,'flat-score-1');assert.equal(h.calls.filter(x=>x.url?.includes('api.flat.io')).length,4);h.click('#score-flat-disconnect');assert.equal(h.w.localStorage.getItem('tuner-flat-token-v1'),null);assert.equal(h.q('#score-flat-open').textContent,'连接 Flat');h.close()});
await test('Flat invalid token shows error, never persists credential (mock only)',async()=>{const h=setup({fetch:(url,opts,res)=>url.includes('api.flat.io')?res({message:'Mock expired'},401):res({user:null})});load(h,'scores.js');await tick();h.q('#score-flat-token').value='fake-token-no-real-access';h.q('#score-flat-form').dispatchEvent(new h.w.Event('submit',{bubbles:true,cancelable:true}));await tick();assert.match(h.q('#score-flat-status').textContent,/Mock expired/);assert.equal(h.w.localStorage.getItem('tuner-flat-token-v1'),null);assert.equal(h.q('#score-flat-connect').disabled,false);h.close()});
await test('Flat cached expired token removed on refresh (mock only)',async()=>{const h=setup({storage:{'tuner-flat-token-v1':'fake'},fetch:(url,opts,res)=>url.includes('api.flat.io')?res({},401):res({user:null})});load(h,'scores.js');await tick();assert.equal(h.w.localStorage.getItem('tuner-flat-token-v1'),null);assert.equal(h.q('#score-flat-open').classList.contains('on'),false);h.close()});
await test('Lesson account cloud state isolation and stale response cancellation (mock only)',async()=>{const h=setup();load(h,'harmony.js');load(h,'lessons.js');await tick();h.click('#favorite-lick');assert.equal(h.q('#favorite-lick').getAttribute('aria-pressed'),'true');const id=h.w.localStorage.getItem('lick-current-id-v1');let resolve;h.w.accountCloud={getLickProgress:()=>new Promise(r=>resolve=r),saveLickProgress:async()=>{}};h.w.dispatchEvent(new h.w.CustomEvent('tuner:account-change',{detail:{user:{id:'A'}}}));assert.equal(h.q('#favorite-lick').getAttribute('aria-pressed'),'false');h.w.dispatchEvent(new h.w.CustomEvent('tuner:account-change',{detail:{user:null}}));assert.equal(h.q('#favorite-lick').getAttribute('aria-pressed'),'true');resolve([{lickId:id,mastered:true,favorite:false}]);await tick();assert.equal(h.q('#favorite-lick').getAttribute('aria-pressed'),'true');h.close()});
await test('Lesson corrupted numeric current index should recover',async()=>{const h=setup({storage:{'lick-current-v2':'bad'}});load(h,'harmony.js');load(h,'lessons.js');assert.match(h.q('#lesson-title').textContent,/Lick/);h.close()});
await test('Lesson hash route after navigating away must return to lesson',async()=>{const h=setup();load(h,'harmony.js');load(h,'lessons.js');h.click('.tab[data-page="lesson"]');h.w.lessonPlayer.select(2);const hash=h.w.location.hash;h.click('.tab[data-page="metro"]');assert.notEqual(h.w.location.hash,hash,'navigating away leaves old lick hash, reload opens wrong page');h.w.location.hash=hash;h.w.dispatchEvent(new h.w.HashChangeEvent('hashchange'));assert.equal(h.q('.tab.active').dataset.page,'lesson');h.close()});
process.exitCode=results.some(result=>result.status==='FAIL')?1:0;for(const r of results)console.log(`${r.status} ${r.name}${r.detail?'\n '+r.detail.split('\n').slice(0,4).join('\n '):''}`);console.log(JSON.stringify({pass:results.filter(r=>r.status==='PASS').length,fail:results.filter(r=>r.status==='FAIL').length}));})();
