const assert=require('assert/strict'),fs=require('fs');const{setup,toneStub,tick}=require('./harness.cjs');const results=[];
async function test(name,fn){try{await fn();results.push({name,status:'PASS'})}catch(e){results.push({name,status:'FAIL',detail:e.stack})}}
(async()=>{
 await test('Shell init & five tabs active panel / aria state',async()=>{const h=setup();assert.equal(h.initError,undefined);for(const page of ['lesson','sheet','metro','jam','tuner']){h.click(`.tab[data-page="${page}"]`);assert.equal(h.q('.tab[aria-current="page"]').dataset.page,page);for(const id of ['lesson','sheet','metro','jam'])assert.equal(h.q('#'+id+'-page').style.display,id===page?'block':'none')}assert.equal(h.errors.length,0);h.close()});
 await test('Account modal login/register/success/logout & server error (simulated)',async()=>{let fail=false;const h=setup({fetch:(url,opts,res)=>res(url.includes('/api/auth/me')?{user:null}:fail?{error:'测试拒绝'}:{user:{username:'qa',displayName:'QA'}},fail?401:200)});await tick();h.click('#account-open');assert.equal(h.q('#account-dialog').open,true);h.click('[data-auth-mode="register"]');assert.equal(h.q('#display-name-field').hidden,false);assert.equal(h.q('#account-form').elements.password.autocomplete,'new-password');h.q('#account-form').elements.username.value='qa';h.q('#account-form').elements.password.value='qa-test';h.q('#account-form').elements.displayName.value='QA';await h.q('#account-form').onsubmit({preventDefault(){}});assert.equal(h.q('#account-open').textContent,'qa');assert.equal(h.q('#account-user').hidden,false);assert.equal(h.calls.at(-1).opts.credentials,'include');await h.q('#account-logout').onclick();assert.equal(h.q('#account-user').hidden,true);fail=true;await h.q('#account-form').onsubmit({preventDefault(){}});assert.equal(h.q('#account-message').textContent,'测试拒绝');assert.equal(h.q('#account-message').classList.contains('error'),true);h.click('#account-close');assert.equal(h.q('#account-dialog').open,false);h.close()});
 await test('Account offline refresh safely leaves logged-out UI',async()=>{const h=setup({fetch:async()=>{throw Error('offline')}});await tick();assert.equal(h.q('#account-auth').hidden,false);assert.equal(h.q('#account-open').textContent,'登录 / 注册');h.close()});
 await test('Microphone accept, A4 detection, stop cleanup, leave tuner cleanup',async()=>{const h=setup();h.click('#toggle');await tick();assert.equal(h.q('#note').textContent,'A');assert.equal(h.q('#octave').textContent,'4');assert.equal(h.w.qa.getRunning(),true);h.click('#toggle');assert.deepEqual(h.mic(),{stopped:1,closed:1});assert.equal(h.raf.size,0);h.click('#toggle');await tick();h.click('.tab[data-page="lesson"]');assert.deepEqual(h.mic(),{stopped:2,closed:2});h.close()});
 await test('Microphone denied leaves retry enabled and clear error',async()=>{const h=setup({getUserMedia:async()=>{throw Error('denied')}});h.click('#toggle');await tick();assert.equal(h.w.qa.getRunning(),false);assert.equal(h.q('#error').style.display,'block');assert.equal(h.q('#toggle').disabled,false);h.close()});
 await test('Microphone pending permission then navigate: stream must be stopped',async()=>{let resolve;const h=setup({getUserMedia:()=>new Promise(r=>resolve=r)});h.click('#toggle');h.click('.tab[data-page="lesson"]');resolve(h.createStream());await tick();assert.equal(h.w.qa.getRunning(),false,'mic continued after leaving tuner while permission pending');assert.equal(h.mic().stopped,1);h.close()});
 await test('Microphone double-click during permission must not leak second stream',async()=>{let resolves=[];const h=setup({getUserMedia:()=>new Promise(r=>resolves.push(r))});h.click('#toggle');h.click('#toggle');for(const r of resolves)r(h.createStream());await tick();h.click('#toggle');assert.equal(h.mic().stopped,h.streams.length,'multiple granted streams but stop cleans only final stream');assert.equal(h.raf.size,0);h.close()});
 await test('Tuner detection: six open guitar strings and silence',()=>{const h=setup();for(const f of[82.4069,110,146.8324,195.9977,246.9417,329.6276]){const b=new Float32Array(4096);for(let i=0;i<b.length;i++)b[i]=.15*Math.sin(2*Math.PI*f*i/48000);const found=h.w.qa.detectPitch(b,48000);assert.ok(Math.abs(1200*Math.log2(found/f))<7,`${f} => ${found}`)}assert.equal(h.w.qa.detectPitch(new Float32Array(4096),48000),-1);h.close()});
 await test('Routes direct #jam and score IDs',()=>{for(const hash of ['#jam','#scores','#score/fur-elise']){const h=setup({url:'https://rexrockya.github.io/tuner/'+hash});assert.equal(h.q('.tab.active').dataset.page,hash==='#jam'?'jam':'sheet');if(hash.startsWith('#score/'))assert.ok(h.calls.some(x=>x.scoreOpen==='fur-elise'));h.close()}});
 await test('Routes direct #metro should open metronome',()=>{const h=setup({url:'https://rexrockya.github.io/tuner/#metro'});assert.equal(h.q('.tab.active').dataset.page,'metro');h.close()});
 await test('Malformed score route must not interrupt initialization',()=>{const h=setup({url:'https://rexrockya.github.io/tuner/#score/%ZZ'});assert.equal(h.errors.length,0,h.errors.join('\n'));h.close()});
 await test('Room invalid input & member controls with valid room (simulated)',async()=>{const h=setup({url:'https://rexrockya.github.io/tuner/?mode=member#metro'});assert.equal(h.q('.tab.active').dataset.page,'metro');h.q('#room-code').value='123';h.click('#remote-send');assert.match(h.q('#remote-status').textContent,/6 位/);h.close();const x=setup({url:'https://rexrockya.github.io/tuner/?mode=member&room=123456#metro'});assert.equal(x.q('#metro-start').style.display,'none');const es=x.calls.find(v=>v.eventSource).eventSource;es.onopen();assert.match(x.q('#remote-status').textContent,/已加入/);es.onmessage({data:JSON.stringify({event:'message',message:JSON.stringify({bpm:112,running:true,timeSignature:[3,4]})})});await tick();assert.equal(x.w.metronome.getBpm(),112);assert.deepEqual([...x.w.metronome.getTimeSignature()],[3,4]);es.onmessage({data:'{malformed'});es.onerror();assert.match(x.q('#remote-status').textContent,/自动重连/);x.close()});
 await test('Room host state publication and offline handling (simulated)',async()=>{const h=setup({url:'https://rexrockya.github.io/tuner/?mode=host&room=654321#metro'});await tick();assert.equal(h.q('#room-code').readOnly,true);assert.ok(h.calls.some(x=>x.url==='https://ntfy.sh/'&&JSON.parse(x.opts.body).topic.includes('654321')));assert.match(h.q('#remote-status').textContent,/已同步/);h.close();const x=setup({url:'https://rexrockya.github.io/tuner/?mode=host&room=654321#metro',fetch:async()=>{throw Error('offline')}});await tick();assert.match(x.q('#remote-status').textContent,/同步失败/);x.close()});
 await test('Jam default/filter/claim/demo/edit/confirm/submit/mix/finalize/fork/reset',async()=>{const h=setup();assert.equal(h.q('#jam-grid').children.length,3);h.click('[data-jam-filter="complete"]');assert.equal(h.q('#jam-grid').children.length,1);h.click('[data-jam-filter="all"]');h.click('[data-open-room="night-lamp"]');assert.equal(h.q('#jam-room-dialog').open,true);h.click('[data-action="claim"][data-role="lead"]');assert.equal(h.w.qa.current().draft.role,'lead');for(const section of h.w.qa.sections){h.click(`[data-action="select-section"][data-section="${section.id}"]`);h.click('[data-action="demo-take"]');assert.ok(h.w.qa.current().draft.sections[section.id].events.length>0);h.click('[data-action="confirm-section"]')}h.click('[data-action="submit-take"]');assert.equal(h.w.qa.current().stage,'mixReady');assert.equal(h.w.qa.current().draft,undefined);h.click('[data-action="be-producer"]');const mix=h.q('[data-mix="lead"]');mix.value='45';mix.dispatchEvent(new h.w.Event('change',{bubbles:true}));assert.equal(h.w.qa.current().mix.lead,45);h.click('[data-action="finalize"]');assert.equal(h.w.qa.current().stage,'complete');assert.equal(h.q('[data-mix="lead"]').disabled,true);h.click('[data-action="fork"]');assert.equal(h.w.qa.rooms().length,4);assert.equal(h.w.qa.current().parent,'night-lamp');h.click('[data-action="close"]');h.click('#jam-reset');assert.equal(h.w.qa.rooms().length,3);assert.equal(h.errors.length,0,h.errors.join('\n'));h.close()});
 await test('Jam empty segment confirmation and submission guard',()=>{const h=setup();h.w.qa.jamOpen('night-lamp');h.click('[data-action="claim"][data-role="lead"]');h.click('[data-action="confirm-section"]');assert.equal(h.w.qa.current().draft.sections[h.w.qa.current().draft.activeSection].confirmed,true);h.click('[data-action="submit-take"]');assert.ok(h.w.qa.current().draft);assert.equal(h.q('[data-action=submit-take]').disabled,true);h.close()});
 await test('Jam form create validation minimum roles and title escaping',()=>{const h=setup();h.click('#jam-create');const form=h.q('#jam-create-form');for(const role of form.querySelectorAll('[name="roles"]'))role.checked=false;form.dispatchEvent(new h.w.Event('submit',{bubbles:true,cancelable:true}));assert.equal(h.w.qa.rooms().length,3);for(const role of [...form.querySelectorAll('[name="roles"]')].slice(0,3))role.checked=true;form.elements.title.value='<img src=x onerror=alert(1)>';form.dispatchEvent(new h.w.Event('submit',{bubbles:true,cancelable:true}));assert.equal(h.w.qa.rooms().length,4);assert.equal(h.q('#jam-room-title').textContent,'<img src=x onerror=alert(1)>');assert.equal(h.q('#jam-room-title img'),null);h.close()});
 await test('Jam simulated playback schedule, stop on navigation',async()=>{const h=setup();const t=toneStub(h.w);h.click('[data-preview="night-lamp"]');await tick();assert.equal(h.w.qa.getSound().roomId,'night-lamp');assert.equal(t.schedules.size,1);for(let i=0;i<32;i++)for(const f of t.schedules.values())f(i*.1);assert.ok(t.log.some(x=>x[0]==='note'));h.click('.tab[data-page="lesson"]');assert.equal(h.w.qa.getSound().roomId,null);assert.equal(t.schedules.size,0);h.close()});
 await test('Jam key release during audio startup should not leave stuck voice',async()=>{let resolve;const h=setup();toneStub(h.w,{start:()=>new Promise(r=>resolve=r)});h.w.qa.jamOpen('night-lamp');h.click('[data-action="claim"][data-role="lead"]');const pending=h.w.qa.jamPress('key-KeyA',60);h.w.qa.jamRelease('key-KeyA');resolve();await pending;assert.equal(h.w.qa.getHeld().size,0,'released key remains held after audio startup resolves');h.close()});
 await test('Jam corrupted JSON safely restores seed',()=>{const h=setup({storage:{'tuner-jam-sections-v3':'{invalid'}});assert.equal(h.initError,undefined);assert.equal(h.w.qa.rooms().length,3);h.close()});
 await test('Jam valid JSON wrong schema must not break every nav tab',()=>{const h=setup({storage:{'tuner-jam-sections-v3':'{}'}});assert.equal(h.initError,undefined);h.click('.tab[data-page="lesson"]');assert.equal(h.q('#lesson-page').style.display,'block');h.close()});
 await test('Storage denied default route still navigates and Jam edits stay usable',()=>{const h=setup({blockStorage:true});assert.equal(h.initError,undefined);h.w.qa.jamOpen('night-lamp');h.click('[data-action="claim"][data-role="lead"]');assert.equal(h.errors.length,0,h.errors.join('\n'));h.close()});
 process.exitCode=results.some(result=>result.status==='FAIL')?1:0;for(const r of results)console.log(`${r.status} ${r.name}${r.detail?'\n '+r.detail.split('\n').slice(0,3).join('\n '):''}`);console.log(JSON.stringify({pass:results.filter(r=>r.status==='PASS').length,fail:results.filter(r=>r.status==='FAIL').length}));
})();
