const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const ROOT=process.env.TUNER_QA_ROOT || path.resolve(__dirname,'../..');
const {setup,tick,raw}=require(path.join(ROOT,'tests/qa/harness.cjs'));
const entries=[...raw.matchAll(/<script\b([^>]*)\bsrc="([^"]+)"[^>]*><\/script>/g)].map(match=>({attrs:match[1],src:match[2]}));
const results=[],rejections=[];let activeWindows=[];
process.on('unhandledRejection',error=>rejections.push(error));
function environment(policy='normal',stored={},url='https://rexrockya.github.io/tuner/') {
  const h=setup({skipApp:true,url,storage:stored,fetch:(url,options,response)=>url.includes('/api/auth/me')?response({user:null}):url.includes('api.flat.io/v2/me')?response({id:'qa',printableName:'Storage QA'}):response([])});
  activeWindows.push(h);delete h.w.metronome;delete h.w.lessonPlayer;delete h.w.scorePlayer;
  const native=h.w.localStorage, flags={property:policy==='getter-denied',read:policy==='read-denied',write:policy==='quota-writes',remove:policy==='remove-denied'};
  const denied=()=>new h.w.DOMException('Storage denied','SecurityError'),quota=()=>new h.w.DOMException('Storage quota exceeded','QuotaExceededError');
  const facade={getItem(key){if(flags.read)throw denied();return native.getItem(key)},setItem(key,value){if(flags.write)throw quota();return native.setItem(key,value)},removeItem(key){if(flags.remove)throw denied();return native.removeItem(key)}};
  Object.defineProperty(h.w,'localStorage',{configurable:true,get(){if(flags.property)throw denied();return facade}});
  return {...h,native,flags,bootstrapErrors:[]};
}
async function boot(policy='normal',stored={},url) {
  const h=environment(policy,stored,url);
  assert.ok(entries.length>=12,'storage adapter must join the real deferred entry scripts');
  assert.ok(entries.some(entry=>entry.src.split('?')[0]==='storage.js'),'storage.js is absent from index');
  for(const entry of entries){assert.match(entry.attrs,/\bdefer\b/);const url=new URL(entry.src,'https://rexrockya.github.io/tuner/');const file=path.join(ROOT,'docs',url.pathname.replace(/^\/tuner\//,''));Object.defineProperty(h.d,'currentScript',{configurable:true,value:{src:url.href}});try{vm.runInContext(fs.readFileSync(file,'utf8'),h.dom.getInternalVMContext(),{filename:file})}catch(error){h.bootstrapErrors.push({file,message:error.message})}}
  // Exercise the same lazy studio entries after the real initial boot.
  for(const name of ['practice-arrangement.js','practice-audio.js','practice.js'])vm.runInContext(fs.readFileSync(path.join(ROOT,'docs',name),'utf8'),h.dom.getInternalVMContext(),{filename:name});
  await tick();assert.deepEqual(h.bootstrapErrors,[],'real script bootstrap failed');assert.ok(h.w.siteStorage,'storage API missing');assert.ok(h.w.lessonPlayer?.activate&&h.w.metronome?.getBpm&&h.w.scorePlayer?.ensureCatalog&&h.w.practiceStudio,'real player APIs missing');assert.deepEqual(h.errors,[]);assert.equal(rejections.length,0,rejections.map(error=>error.stack).join('\n'));return h;
}
function notice(h){const element=h.q('#storage-notice');assert.ok(element);assert.equal(element.getAttribute('role'),'status');assert.equal(element.hidden,false);assert.match(element.textContent,/本机存储不可用/);assert.match(element.textContent,/刷新后丢失/)}
async function usable(h,{volatile=false}={}) {
  for(const page of['lesson','sheet','metro','jam','tuner']){h.click(`.tab[data-page="${page}"]`);assert.equal(h.q('.tab.active').dataset.page,['metro','tuner'].includes(page)?'tools':page);assert.equal(h.q('.tab[aria-current="page"]').dataset.page,['metro','tuner'].includes(page)?'tools':page)}
  h.w.metronome.setBpm(115);assert.equal(h.w.metronome.getBpm(),115);assert.equal(h.q('#metro-bpm').textContent,'115');
  h.w.metronome.setVolume(57);assert.equal(h.q('#metro-volume-value').textContent,'57%');h.w.scorePlayer.setVolume(63);assert.equal(h.q('#sheet-instrument-volume-value').textContent,'63%');
  h.click('.tab[data-page="lesson"]');h.w.lessonPlayer.select(2);assert.match(h.q('#lesson-title').textContent,/Lick 3/);h.click('#favorite-lick');assert.equal(h.q('#favorite-lick').getAttribute('aria-pressed'),'true');h.click('#favorites-open');assert.ok(h.q('#favorites-list').textContent.includes('Lick 3'));h.click('#favorites-close');
  h.click('[data-lesson-mode="create"]');assert.equal(h.q('#practice-play').disabled,false);h.click('#practice-save');assert.equal(h.q('#practice-saved').options.length,2);if(volatile){assert.equal(h.q('#practice-save').textContent,'本次暂存');assert.match(h.q('#practice-error').textContent,/MIDI/);notice(h)}else assert.equal(h.q('#practice-save').textContent,'已收藏');
  h.click('.tab[data-page="jam"]');h.click('[data-open-room="night-lamp"]');h.click('[data-action="claim"][data-role="lead"]');h.click('[data-action="demo-take"]');assert.ok(h.q('[data-note-id]'));const rooms=JSON.parse(h.w.siteStorage.getItem('tuner-jam-sections-v3'));const room=rooms.find(item=>item.id==='night-lamp');assert.equal(room.draft.role,'lead');assert.ok(room.draft.sections[room.draft.activeSection].events.length);h.click('[data-action="close"]');
  await tick();assert.deepEqual(h.errors,[]);assert.equal(rejections.length,0,rejections.map(error=>error.stack).join('\n'));
}
async function test(name,fn){activeWindows=[];rejections.length=0;try{await fn();results.push({name,status:'PASS'})}catch(error){results.push({name,status:'FAIL',detail:error.stack})}finally{await tick();for(const h of activeWindows)h.close();}}
(async()=>{
  await test('Storage normal boot and functional persistence',async()=>{const h=await boot();await usable(h);const storage=h.w.siteStorage;assert.equal(storage.setItem('qa-value','one'),true);assert.equal(storage.getItem('qa-value'),'one');assert.equal(h.native.getItem('qa-value'),'one');assert.equal(storage.removeItem('qa-value'),true);assert.equal(storage.getItem('qa-value'),null);assert.equal(h.native.getItem('qa-value'),null)});
  await test('Storage property getter denied: all real scripts, navigation and editing survive',async()=>{const h=await boot('getter-denied');await usable(h,{volatile:true});assert.equal(h.w.siteStorage.setItem('qa-value','memory'),false);assert.equal(h.w.siteStorage.getItem('qa-value'),'memory')});
  await test('Storage getItem denied: defaults, navigation and controls remain usable',async()=>{const h=await boot('read-denied');await usable(h);notice(h);assert.equal(h.w.siteStorage.getItem('missing-key'),null)});
  await test('Storage initial quota exhausted: favorites, original saves and Jam are session-only',async()=>{const h=await boot('quota-writes');await usable(h,{volatile:true});assert.equal(h.native.getItem('tuner-original-licks-v1'),null);assert.equal(h.native.getItem('tuner-jam-sections-v3'),null)});
  await test('Storage becomes unavailable after boot; failed writes shadow stale values and retry can persist',async()=>{const h=await boot();const storage=h.w.siteStorage;assert.equal(storage.setItem('qa-value','old'),true);h.flags.write=true;assert.equal(storage.setItem('qa-value','new'),false);assert.equal(storage.getItem('qa-value'),'new');assert.equal(h.native.getItem('qa-value'),'old');await usable(h,{volatile:true});h.flags.write=false;assert.equal(storage.setItem('qa-value','recovered'),true);assert.equal(h.native.getItem('qa-value'),'recovered');assert.equal(storage.getItem('qa-value'),'recovered')});
  await test('Storage failed delete is a tombstone; Flat disconnect cannot resurrect cached token',async()=>{const h=await boot();const token='mock-token-for-storage-test-only';await h.w.scorePlayer.connectFlat(token);assert.equal(h.native.getItem('tuner-flat-token-v1'),token);h.flags.remove=true;h.w.scorePlayer.disconnectFlat();assert.equal(h.w.siteStorage.getItem('tuner-flat-token-v1'),null);assert.equal(h.native.getItem('tuner-flat-token-v1'),token);assert.equal(h.q('#score-flat-open').classList.contains('on'),false);assert.equal(h.w.siteStorage.removeItem('tuner-flat-token-v1'),false);h.flags.remove=false;assert.equal(h.w.siteStorage.removeItem('tuner-flat-token-v1'),true);assert.equal(h.native.getItem('tuner-flat-token-v1'),null);assert.equal(h.w.siteStorage.getItem('tuner-flat-token-v1'),null)});
  await test('Storage property permission can recover without a reload or lost current edits',async()=>{const h=await boot('getter-denied');const storage=h.w.siteStorage;assert.equal(storage.setItem('qa-recovery','session'),false);assert.equal(storage.getItem('qa-recovery'),'session');h.flags.property=false;assert.equal(storage.setItem('qa-recovery','persisted'),true);assert.equal(h.native.getItem('qa-recovery'),'persisted');assert.equal(storage.getItem('qa-recovery'),'persisted');assert.equal(storage.removeItem('qa-recovery'),true);assert.equal(storage.getItem('qa-recovery'),null)});

  await test('Flat failed disconnect keeps cleanup warning visible and preserves it on reopen',async()=>{const h=await boot();await h.w.scorePlayer.connectFlat('mock-token-for-visible-warning');h.click('#score-flat-open');h.flags.remove=true;h.click('#score-flat-disconnect');assert.equal(h.q('#score-flat-dialog').open,true,'failed credential deletion must not immediately hide its warning');assert.match(h.q('#score-flat-status').textContent,/未能清除本机授权/);h.click('#score-flat-close');h.click('#score-flat-open');assert.match(h.q('#score-flat-status').textContent,/未能清除本机授权/);assert.equal(h.w.siteStorage.getItem('tuner-flat-token-v1'),null)});
  await test('Flat temporary connection makes its persistence limit visible across dialog reopening',async()=>{const h=await boot();h.flags.write=true;h.click('#score-flat-open');h.q('#score-flat-token').value='mock-token-for-session-only';h.q('#score-flat-form').dispatchEvent(new h.w.Event('submit',{bubbles:true,cancelable:true}));await tick();assert.match(h.q('#score-flat-status').textContent,/仅本次/);for(const timer of [...h.timeouts.values()].filter(timer=>timer.ms===500))timer.fn();assert.equal(h.q('#score-flat-dialog').open,true,'temporary connection notice must not auto-dismiss');h.click('#score-flat-close');h.click('#score-flat-open');assert.match(h.q('#score-flat-status').textContent,/仅本次/)});

  await test('Storage quota does not prevent creating and entering a metronome host room',async()=>{const h=await boot('quota-writes',{},'https://rexrockya.github.io/tuner/?mode=host#metro');assert.equal(h.q('.tab.active').dataset.page,'tools');assert.match(h.q('#room-code').value,/^\d{6}$/);assert.equal(h.q('#room-code').readOnly,true);assert.equal(h.w.siteStorage.getItem('tuner-room-code-v1'),h.q('#room-code').value);assert.equal(h.native.getItem('tuner-room-code-v1'),null);assert.ok(h.calls.some(call=>call.url==='https://ntfy.sh/'&&call.opts.method==='POST'));h.click('.tab[data-page="lesson"]');assert.equal(h.q('.tab.active').dataset.page,'lesson');notice(h)});
  for(const r of results)console.log(`${r.status} ${r.name}${r.detail?'\n'+r.detail:''}`);console.log(JSON.stringify({pass:results.filter(r=>r.status==='PASS').length,fail:results.filter(r=>r.status==='FAIL').length}));process.exitCode=results.some(r=>r.status==='FAIL')?1:0;
})().catch(error=>{console.error(error);process.exitCode=1});
